

db_url: mongodb://mongo:27017/db


skema_path: domain.skema


types:
    EventWindow:
        collection: events
        pipeline:
            -   $group:
                    _id:
                        $subtract:
                            - $timestamp
                            - $mod: [$timestamp, 60000] # minute 60 * 1000
                    count:
                        $sum: 1
            -   $project:
                    timestamp: $_id
                    count: 1

# relations:
#     -   from: Bot
#         to: EventWindow
#         relation_type: to_many
#         field: likes_over_time
#         query: {}



