
version: '3'

services:
    api:
        ports:
            - 8090:80
        image: mongoke/mongoke:latest
        environment: 
            - DB_URL=mongodb://mongo/db
            - PYTHONUNBUFFERED=1
        volumes: 
            - ./mongoke.yml:/conf.yml
            # - ./domain.skema:/domain.skema
    populate-db:
        image: mongoke/populate-mongo
        volumes:
            - ./mongoke.yml/:/conf.yml
        environment:
            - DB_URL=mongodb://mongo/db
    mongo:
        ports:
            - 27017:27017
        image: mongo
        logging: 
            driver: none

